{% set version = "1.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyverse
  version: {{ version|replace("-", "_") }}

source:
  fn: tidyverse_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidyverse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyverse/tidyverse_{{ version }}.tar.gz
  sha256: 6d8acb81e994f9bef5e4dcf908bcea3786d108adcf982628235b6c8c80f6fe09

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-broom >=0.5.2
    - r-cli >=1.1.0
    - r-crayon >=1.3.4
    - r-dbplyr >=1.4.2
    - r-dplyr >=0.8.3
    - r-forcats >=0.4.0
    - r-ggplot2 >=3.2.1
    - r-haven >=2.2.0
    - r-hms >=0.5.2
    - r-httr >=1.4.1
    - r-jsonlite >=1.6
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-modelr >=0.1.5
    - r-pillar >=1.4.2
    - r-purrr >=0.3.3
    - r-readr >=1.3.1
    - r-readxl >=1.3.1
    - r-reprex >=0.3.0
    - r-rlang >=0.4.1
    - r-rstudioapi >=0.10
    - r-rvest >=0.3.5
    - r-stringr >=1.4.0
    - r-tibble >=2.1.3
    - r-tidyr >=1.0.0
    - r-xml2 >=1.2.2
  run:
    - r-base
    - r-broom >=0.5.2
    - r-cli >=1.1.0
    - r-crayon >=1.3.4
    - r-dbplyr >=1.4.2
    - r-dplyr >=0.8.3
    - r-forcats >=0.4.0
    - r-ggplot2 >=3.2.1
    - r-haven >=2.2.0
    - r-hms >=0.5.2
    - r-httr >=1.4.1
    - r-jsonlite >=1.6
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-modelr >=0.1.5
    - r-pillar >=1.4.2
    - r-purrr >=0.3.3
    - r-readr >=1.3.1
    - r-readxl >=1.3.1
    - r-reprex >=0.3.0
    - r-rlang >=0.4.1
    - r-rstudioapi >=0.10
    - r-rvest >=0.3.5
    - r-stringr >=1.4.0
    - r-tibble >=2.1.3
    - r-tidyr >=1.0.0
    - r-xml2 >=1.2.2

test:
  commands:
    - $R -e "library('tidyverse')"           # [not win]
    - "\"%R%\" -e \"library('tidyverse')\""  # [win]

about:
  home: http://tidyverse.tidyverse.org, https://github.com/tidyverse/tidyverse
  license: GPL-3
  summary: The 'tidyverse' is a set of packages that work in harmony because they share common
    data representations and 'API' design. This package is designed to make it easy
    to install and load multiple 'tidyverse' packages in a single step. Learn more about
    the 'tidyverse' at <https://tidyverse.org>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
