{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyverse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyverse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyverse/tidyverse_{{ version }}.tar.gz
  sha256: 3d3c2d135056333247d309d1c2cc98cc0d87e2c781f4c6fbceab28d28c0728e5

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-broom >=1.0.3
    - r-conflicted >=1.2.0
    - r-cli >=3.6.0
    - r-dbplyr >=2.3.0
    - r-dplyr >=1.1.0
    - r-dtplyr >=1.2.2
    - r-forcats >=1.0.0
    - r-ggplot2 >=3.4.1
    - r-googledrive >=2.0.0
    - r-googlesheets4 >=1.0.1
    - r-haven >=2.5.1
    - r-hms >=1.1.2
    - r-httr >=1.4.4
    - r-jsonlite >=1.8.4
    - r-lubridate >=1.9.2
    - r-magrittr >=2.0.3
    - r-modelr >=0.1.10
    - r-pillar >=1.8.1
    - r-purrr >=1.0.1
    - r-ragg >=1.2.5
    - r-readr >=2.1.4
    - r-readxl >=1.4.2
    - r-reprex >=2.0.2
    - r-rlang >=1.0.6
    - r-rstudioapi >=0.14
    - r-rvest >=1.0.3
    - r-stringr >=1.5.0
    - r-tibble >=3.1.8
    - r-tidyr >=1.3.0
    - r-xml2 >=1.3.3
  run:
    - r-base
    - r-broom >=1.0.3
    - r-conflicted >=1.2.0
    - r-cli >=3.6.0
    - r-dbplyr >=2.3.0
    - r-dplyr >=1.1.0
    - r-dtplyr >=1.2.2
    - r-forcats >=1.0.0
    - r-ggplot2 >=3.4.1
    - r-googledrive >=2.0.0
    - r-googlesheets4 >=1.0.1
    - r-haven >=2.5.1
    - r-hms >=1.1.2
    - r-httr >=1.4.4
    - r-jsonlite >=1.8.4
    - r-lubridate >=1.9.2
    - r-magrittr >=2.0.3
    - r-modelr >=0.1.10
    - r-pillar >=1.8.1
    - r-purrr >=1.0.1
    - r-ragg >=1.2.5
    - r-readr >=2.1.4
    - r-readxl >=1.4.2
    - r-reprex >=2.0.2
    - r-rlang >=1.0.6
    - r-rstudioapi >=0.14
    - r-rvest >=1.0.3
    - r-stringr >=1.5.0
    - r-tibble >=3.1.8
    - r-tidyr >=1.3.0
    - r-xml2 >=1.3.3

test:
  commands:
    - $R -e "library('tidyverse')"           # [not win]
    - "\"%R%\" -e \"library('tidyverse')\""  # [win]

about:
  home: https://tidyverse.tidyverse.org
  dev_url: https://github.com/tidyverse/tidyverse
  doc_url: https://tidyverse.tidyverse.org/reference/
  license: MIT
  summary: The 'tidyverse' is a set of packages that work in harmony because they share common data representations and 'API' design. This package is designed to make it easy to install and load multiple 'tidyverse' packages in a single step. Learn more about the 'tidyverse' at <https://tidyverse.org>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
