appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: c5GqcxszolzeiBEYzOgjcQgiDHhSHrpEnACTW3ua+fT+CFTmanSXdi08tuinfDNSDgGUEmwdGKje+xaotMHsKdq8HeYDPzUVvjZYbsqn7p/cS0rYJJEzYnB0VNvkLQQxrHsjnMXJdY0osMgpGDq8poOo+n4vsNIw6EIE9dfF5cbL4T/s1jXFys7/dwo3exfQM5aBYRE44MObgrAEwLYH4D0iwXITwh6Ag58MVpjeyU/KG1l6EWaMI5TeNfuYAU7w7Is7mNeftNgRguT/NnNaRHjG7FNzCl8cJ8DneR1NM0tWhjgTpu25TRohikyCcHsAYBnUrTYAPUFq/7XZ3rue1fTd/uSYjZrElXZW/R7cU2gMpm0L62y5JxHhKesKncHUMG7HQ8PBW+Y9uwtgbGguFdchCzYVgVV/g2+S9cK09qmDKLs2T1hXnbBAdoVpkSGQje02mS1Ycy78X9jGvJZ/W3AdjFCqD0VcNy4RcfkIjrDFkFpqBc5dIeAKqz1rnEFDOArT0ml2jU0Ba50mErvp0hjc+G68dVSdpuBmf+UTPAHTM4jlNBVek1rMRat3ihyNJDP1RK6BM8hL4GzE/Ra5fgIMvkkPl9PlhXufl/vxJGIPWHdfnduEHfpPdzCf6ih7C86Etv6QZRy1K3mfWwEzH1ARCu7IKgvqhkRyODTtHc0=
conda_forge_output_validation: true
